/*
 * @link https://www.algernon.io/
 * @license https://github.com/AlgernonLabs/algernon/blob/master/LICENSE.md
 */

module.exports = Object.freeze({
  PREMIUM_SUBSCRIPTION_REQUIRED: "PREMIUM_SUBSCRIPTION_REQUIRED",
  EXCEEDED_ENTITY_LIMIT: "EXCEEDED_ENTITY_LIMIT",
  VALIDATION_FAILURE: "VALIDATION_FAILURE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  USER_DOES_NOT_EXIST: "USER_DOES_NOT_EXIST",
  NOTHING_FOUND: "NOTHING_FOUND",
  EMAIL_IS_ALREADY_USED: "EMAIL_IS_ALREADY_USED",
  INVALID_LOGIN: "INVALID_LOGIN",
  INVALID_EMAIL_CONFIRMATION_TOKEN: "INVALID_EMAIL_CONFIRMATION_TOKEN",
  EMAIL_CONFIRMATION_TOKEN_ALREADY_USED:
    "EMAIL_CONFIRMATION_TOKEN_ALREADY_USED",
  INVALID_PASSWORD_RESET_TOKEN: "INVALID_PASSWORD_RESET_TOKEN",
  USER_HAS_ALREADY_UPGRADED: "USER_HAS_ALREADY_UPGRADED"
});
